query popularSearches(
  $page: Int
  $limit: Int
  $search: String
  $sort: String
  $store: ID
  $domain: String
) {
  popularSearches(
    page: $page
    search: $search
    limit: $limit
    sort: $sort
    store: $store
    domain: $domain
  ) {
    count
    page
    pageSize
    data {
      id
      text
      popularity
      store {
        id
        name
        email
        phone
      }
    }
  }
}
