mutation changePassword($oldPassword: String!, $password: String!, $passwordConfirmation: String!) {
	changePassword(
		oldPassword: $oldPassword
		password: $password
		passwordConfirmation: $passwordConfirmation
	)
}
