mutation verifyOtp($phone: String!, $otp: String!, $store: ID) {
	verifyOtp(phone: $phone, otp: $otp, store: $store) {
		id
		firstName
		lastName
		email
		phone
		role
		verified
		active
		avatar
		avatarCdn
		sid
	}
}
