mutation stripe($address: ID, $paymentMethodId: String, $slot: ID) {
	stripe(address: $address, paymentMethodId: $paymentMethodId, slot: $slot) {
		id
		paymentOrderId
		paymentMode
		paymentGateway
		referenceId
		txMsg
		txTime
		invoiceId
		receipt
		paid
		amountPaid
		amountDue
		amountRefunded
		currency
		captured
		status
		orderId
		notes
		refundStatus
		description
		email
		contact
		fee
		tax
		errorCode
		errorDescription
		token
		clientSecret
		approvalUrl
	}
}
