/**
 * Generators - turn design-tokens.json into drop-in files for svelte-commerce:
 *   theme.css          shadcn-style HSL CSS variables (:root block)
 *   tailwind.theme.cjs Tailwind theme extension (require()-able from tailwind.config)
 *   store.config.json  store-level metadata (name, logo, fonts, meta)
 *   fonts.html         <link> tags for Google Fonts (paste into app.html)
 *   REPORT.md          human-readable summary + confidence notes
 */
import { hsl, parse as parseColor } from 'culori';

export function generateThemeCss(tokens) {
  const r = tokens.palette.roles;
  const toHslTriplet = (hex) => {
    const c = hsl(parseColor(hex));
    return `${(c.h ?? 0).toFixed(1)} ${((c.s ?? 0) * 100).toFixed(1)}% ${(c.l * 100).toFixed(1)}%`;
  };

  const vars = Object.entries(r)
    .map(([name, hex]) => `  --${name}: ${toHslTriplet(hex)};`)
    .join('\n');

  return `/* AUTO-GENERATED by varni-reskin - do not edit by hand.
 * Source: ${tokens.source.files.join(', ')}
 * Generated: ${tokens.generatedAt}
 * Drop into src/app.css (or app.pcss) replacing the existing :root block.
 */
:root {
${vars}
  --radius: ${tokens.geometry.radius};
  --font-heading: '${tokens.typography.fontHeading}', serif;
  --font-body: '${tokens.typography.fontBody}', sans-serif;
  --shadow-default: ${tokens.geometry.shadow};
  --container-width: ${tokens.geometry.containerWidth};
  --transition-duration: ${tokens.geometry.transitionDuration};
}

body {
  font-family: var(--font-body);
}

h1, h2, h3, h4, h5, h6 {
  font-family: var(--font-heading);
  letter-spacing: ${tokens.typography.letterSpacingHeading};
}
`;
}

export function generateTailwindTheme(tokens) {
  const r = tokens.palette.roles;
  const theme = {
    colors: {
      background: 'hsl(var(--background) / <alpha-value>)',
      foreground: 'hsl(var(--foreground) / <alpha-value>)',
      primary: { DEFAULT: 'hsl(var(--primary) / <alpha-value>)', foreground: 'hsl(var(--primary-foreground) / <alpha-value>)' },
      secondary: { DEFAULT: 'hsl(var(--secondary) / <alpha-value>)', foreground: 'hsl(var(--secondary-foreground) / <alpha-value>)' },
      accent: { DEFAULT: 'hsl(var(--accent) / <alpha-value>)', foreground: 'hsl(var(--accent-foreground) / <alpha-value>)' },
      muted: { DEFAULT: 'hsl(var(--muted) / <alpha-value>)', foreground: 'hsl(var(--muted-foreground) / <alpha-value>)' },
      card: { DEFAULT: 'hsl(var(--card) / <alpha-value>)', foreground: 'hsl(var(--card-foreground) / <alpha-value>)' },
      destructive: { DEFAULT: 'hsl(var(--destructive) / <alpha-value>)', foreground: 'hsl(var(--destructive-foreground) / <alpha-value>)' },
      border: 'hsl(var(--border) / <alpha-value>)',
      input: 'hsl(var(--input) / <alpha-value>)',
      ring: 'hsl(var(--ring) / <alpha-value>)',
      // Literal hexes too, for stores still on hardcoded Tailwind colors.
      brand: { DEFAULT: r.primary, secondary: r.secondary, accent: r.accent },
    },
    fontFamily: {
      heading: [tokens.typography.fontHeading, 'serif'],
      sans: [tokens.typography.fontBody, 'ui-sans-serif', 'system-ui'],
      body: [tokens.typography.fontBody, 'ui-sans-serif', 'system-ui'],
    },
    borderRadius: {
      DEFAULT: 'var(--radius)',
      lg: 'calc(var(--radius) + 4px)',
      md: 'var(--radius)',
      sm: 'calc(var(--radius) - 2px)',
    },
    boxShadow: { DEFAULT: tokens.geometry.shadow },
    maxWidth: { container: tokens.geometry.containerWidth },
  };
  return `/* AUTO-GENERATED by varni-reskin.
 * In tailwind.config.js: theme: { extend: require('./theme/tailwind.theme.cjs') }
 */
module.exports = ${JSON.stringify(theme, null, 2)};
`;
}

export function generateStoreConfig(tokens, structure) {
  return JSON.stringify({
    name: structure.meta.ogSiteName || structure.meta.title || 'Varni Store',
    description: structure.meta.description || '',
    logo: structure.assets.logo || null,
    favicon: structure.assets.favicon || null,
    themeColor: tokens.palette.roles.primary,
    fonts: tokens.typography.googleFontFamilies,
    generatedAt: tokens.generatedAt,
  }, null, 2);
}

export function generateFontsHtml(tokens, structure) {
  if (structure.googleFonts.length) {
    return structure.googleFonts.map((h) => `<link rel="stylesheet" href="${h.startsWith('http') ? h : 'https:' + h}">`).join('\n') + '\n';
  }
  const fams = tokens.typography.googleFontFamilies
    .map((f) => `family=${encodeURIComponent(f).replace(/%20/g, '+')}:wght@${tokens.typography.fontWeights.join(';')}`)
    .join('&');
  return `<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?${fams}&display=swap">
`;
}

export function generateReport(tokens, structure) {
  const r = tokens.palette.roles;
  const swatch = (name) => `| ${name} | \`${r[name]}\` |`;
  const warnings = [];
  if (tokens.palette.confidence.contrastFgOnBg < 4.5) {
    warnings.push(`- Body text contrast is ${tokens.palette.confidence.contrastFgOnBg}:1 (< 4.5:1 WCAG AA) - inherited from source design.`);
  }
  if (tokens.palette.confidence.contrastPrimaryOnBg < 3) {
    warnings.push(`- Primary-on-background contrast is ${tokens.palette.confidence.contrastPrimaryOnBg}:1 - buttons may be hard to see.`);
  }
  if (String(tokens.palette.confidence.primary).startsWith('low')) {
    warnings.push(`- ${tokens.palette.confidence.primary}`);
  }

  return `# Reskin Report

**Source files:** ${tokens.source.files.join(', ')}
**Generated:** ${tokens.generatedAt}
**Store:** ${structure.meta.title || 'unknown'}

## Palette (auto-assigned roles)
| Role | Hex |
|---|---|
${['background', 'foreground', 'primary', 'secondary', 'accent', 'muted', 'border', 'destructive'].map(swatch).join('\n')}

## Typography
- Heading: **${tokens.typography.fontHeading}**
- Body: **${tokens.typography.fontBody}**
- Weights: ${tokens.typography.fontWeights.join(', ')}

## Geometry
- Radius: \`${tokens.geometry.radius}\` - Shadow: \`${tokens.geometry.shadow}\`
- Container: \`${tokens.geometry.containerWidth}\` - Transition: \`${tokens.geometry.transitionDuration}\`

## Sections detected for AI restyle
${Object.keys(structure.sections).length ? Object.keys(structure.sections).map((s) => `- ${s}`).join('\n') : '- none detected'}

${warnings.length ? '## Warnings\n' + warnings.join('\n') : 'No warnings.'}

## Top source colors (by weight)
${tokens.palette.fullPalette.slice(0, 10).map((c) => `- \`${c.hex}\` x${c.count} ${c.contexts.length ? '(' + c.contexts.join(', ') + ')' : ''}`).join('\n')}
`;
}
