query addresses(
  $page: Int
  $search: String
  $limit: Int
  $sort: String
  $store: ID
) {
  addresses(
    page: $page
    search: $search
    limit: $limit
    sort: $sort
    store: $store
  ) {
    count
    page
    pageSize
    data {
      id
      email
      firstName
      lastName
      address
      locality
      town
      city
      country
      state
      zip
      phone
      lat
      lng
      active
      verified
      createdAt
      updatedAt
      store
    }
  }
}
