import { test, expect } from '@playwright/test'

import { app_url } from './config'

// test('test', async ({ page }) => {
// 	await page.goto(app_url)
// 	await page.getByLabel('/').click()
// 	await page.getByLabel('Email address').dblclick()
// 	await page.getByLabel('Email address').press('Meta+a')
// 	await page.getByLabel('Email address').fill('hi@litekart.in')
// 	await page.getByLabel('Email address').press('Tab')
// 	await page.getByLabel('Password').fill('litekart')
// 	await page.getByLabel('Password').press('Enter')
// 	await page.waitForURL(app_url)
// 	await page.waitForLoadState()
// 	await page.goto('http://localhost:3000/my/profile')
// 	await page.click('a[href="/my/addresses?sort=-updatedAt"]')
// 	await page.getByRole('button', { name: 'Add New Address' }).click()
//     await page.waitForLoadState()
//     await page.getByPlaceholder('Enter Postal Code/Pincode/Zipcode').dblclick()
// 	await page.getByPlaceholder('Enter Postal Code/Pincode/Zipcode').fill('777777')
// 	await page.getByPlaceholder('Enter City').dblclick()
//     await page.fill('input[placeholder="Enter City"]', 'hi@litekart.in')
// 	await page.getByRole('combobox').nth(1).selectOption('US')
// 	await page.getByRole('button', { name: 'Save Address' }).click()
// 	await page.waitForLoadState()
// 	await page.getByRole('button', { name: 'Save Address' }).click()
// 	await page.waitForLoadState()
// 	await page.waitForURL('http://localhost:3000/my/addresses?sort=-updatedAt')
// })

test('edit address', async ({ page }) => {
	await page.goto(app_url)
	await page.getByLabel('/').click()
	await page.getByLabel('Email address').dblclick()
	await page.getByLabel('Email address').press('Meta+a')
	await page.getByLabel('Email address').fill('hi@litekart.in')
	await page.getByLabel('Email address').press('Tab')
	await page.getByLabel('Password').fill('litekart')
	await page.getByLabel('Password').press('Enter')
	await page.waitForURL(app_url)
	await page.waitForLoadState()
	await page.goto(`${app_url}my/profile`)
	await page.click('a[href="/my/addresses?sort=-updatedAt"]')
	await page.click('a[aria-label="Click to visit address details"]')
	await page.getByPlaceholder('Enter Address').click()
	await page.getByPlaceholder('Enter Address').fill('11 rue toast2 new road')
	await page.getByRole('button', { name: 'Save Address' }).click()
	await page.waitForURL(`${app_url}my/addresses?sort=-updatedAt`)
})
