query reviews($page: Int, $search: String, $limit: Int, $sort: String, $store: ID) {
	reviews(page: $page, search: $search, limit: $limit, sort: $sort, store: $store) {
		count
		page
		pageSize
		data {
			id
			rating
			message
			active
			createdAt
			updatedAt
			# listing {
			# 	id
			# }
			pid {
				name
				slug
				img
				imgCdn
				type
			}
			user {
				firstName
				lastName
				phone
			}
			vendor {
				id
				slug
				businessName
				banner
				bannerCdn
			}
			store {
				id
				name
				email
			}
		}
	}
}
