query HOME($store: ID, $zip: String) {
	brands(parent: null, limit: 30, page: 0, featured: true, store: $store) {
		count
		page
		pageSize
		data {
			id
			brandId
			name
			slug
			img
			imgCdn
			position
			info
			meta
			metaTitle
			metaDescription
			metaKeywords
			facebookUrl
			instaUrl
			twitterUrl
			linkedinUrl
			youtubeUrl
			pinterestUrl
			googleUrl
			active
			featured
			parent {
				id
				name
			}
			store {
				id
				name
				email
				phone
				active
			}
			createdAt
			updatedAt
		}
	}
	categories(img: true, shopbycategory: true, store: $store, sort: "featuredSort") {
		count
		page
		pageSize
		data {
			id
			name
			namePath
			categoryId
			parent
			slug
			img
			imgCdn
			link
			level
			metaTitle
			metaDescription
			metaKeywords
			position
			megamenu
			active
			featured
			shopbycategory
			createdAt
			updatedAt
			store
		}
	}
	banners(sort: "sort", pageId: "home", active: true, store: $store) {
		count
		page
		pageSize
		data {
			id
			link
			heading
			img
			imgCdn
			sort
			type
			pageId
			groupId
			groupTitle
			active
			isMobile
			createdAt
			updatedAt
			store
		}
	}
	youMayLike(store: $store) {
		id
		sku
		barcode
		description
		productMasterId
		slug
		name
		type
		foodType
		price
		mrp
		stock
		tax
		img
		imgCdn
		images
		imagesCdn
		time
		active
		popularity
		position
		trending
		featured
		hot
		new
		sale
		recommended
		title
		metaDescription
		keywords
		ratings
		reviews
		itemId
		warranty
		discount
		ageMin
		ageMax
		ageUnit
		cgst
		sgst
		igst
		returnInfo
		description
		keyFeatures
		expiryDate
		vendor {
			businessName
		}
		productDetails {
			name
			value
		}
		specifications {
			name
			value
		}
		countryOfOrigin
		stock
	}
	trending(type: "hot", store: $store) {
		id
		sku
		barcode
		description
		productMasterId
		slug
		name
		type
		foodType
		price
		mrp
		stock
		tax
		img
		imgCdn
		images
		imagesCdn
		time
		active
		popularity
		position
		trending
		featured
		hot
		new
		sale
		recommended
		title
		metaDescription
		keywords
		ratings
		reviews
		itemId
		warranty
		discount
		ageMin
		ageMax
		ageUnit
		cgst
		sgst
		igst
		returnInfo
		description
		keyFeatures
		expiryDate
		vendor {
			businessName
		}
		productDetails {
			name
			value
		}
		specifications {
			name
			value
		}
		countryOfOrigin
		stock
	}
	popular(store: $store, page: 0, zip: $zip) {
		data {
			id
			slug
			name
			type
			price
			mrp
			discount
			stock
			img
			imgCdn
			images
			imagesCdn
			time
			ratings
			reviews
			zips
			foodType
			expiryDate
			vendor {
				id
				slug
				businessName
				banner
				bannerCdn
			}
		}
		count
		pageSize
		page
	}
	groupByBanner(active: true, pageId: "home", store: $store) {
		_id {
			title
			type
		}
		data {
			link
			heading
			img
			imgCdn
			sort
			type
			pageId
			store
			active
			groupId
			groupTitle
			createdAt
			updatedAt
		}
	}
}
