query store {
	store {
		id
		active
		adminNotifications {
			lowStockNotification
			newOrderPlaced
		}
		address
		alert
		analyticsTrackingId
		banners
		city
		closed
		closedMessage
		customerOrderNotifications {
			downloadEGoods
			giftCardPurchased
			orderConfirmation
			orderIsReadyForPickup
			orderShipped
			orderStatusChanged
			orderConfirmationSms
		}
		vendorNotifications {
			orderConfirmationSms
		}
		description
		metaDescription
		dimentionUnit
		domain
		email
		facebook
		facebookPixelId
		facebookUrl
		favicon
		faviconCdn
		firstName
		freeShippingOn
		gdpr
		gdprCookieConsent
		google
		googleAdsTag
		homeMeta1
		homeMeta2
		homeMeta3
		homeMeta4
		img
		imgCdn
		images
		imagesCdn
		instagram
		instagramUrl
		isHideNilStock
		isMegamenu
		isOpen
		isSearch
		isHyperlocal
		isFnb
		isWishlist
		isCart
		keywords
		lastName
		lat
		legalName
		linkedin
		lng
		locality
		logo
		logoDark
		logoMobile
		logoMobileDark
		logoCdn
		logoDarkCdn
		logoMobileCdn
		logoMobileDarkCdn
		minimumOrderValue
		name
		openGraphImage
		openGraphImageCdn
		pageSize
		phone
		pinterestTag
		pinterestUrl
		qrCode
		review {
			enabled
			moderate
		}
		searchbarText
		shipping {
			charge
			deliveryDays
			enabled
			free
			method
			provider
		}
		shippingCharge
		shopAddress
		shopPhone
		slug
		snapChatPixel
		state
		storeId
		bankAccountNo
		bankAccountHolderName
		bankIfscCode
		bankSwiftCode
		timeZone
		timing
		title
		twitter
		twitterUrl
		websiteEmail
		websiteLegalName
		websiteName
		weightUnit
		youtubeUrl
		webmail
		zip
		timeDisplayFormat
		priceDisplayFormat
		createdAt
		updatedAt
		user
		sms {
			AUTO_VERIFICATION_ID
		}
		shippoToken
		shipRocketEmail
		shipRocketPassword
		shipRocketChannelId
		pickrrAuthToken
		storeTiming {
			day
			fromTime
			index
			isOpen
			online
			toTime
		}
	}
}
