mutation addToCart(
  $qty: Int!
  $pid: ID!
  $vid: ID
  $options: [OptionIp1]
  $vendor: ID
  $replace: Boolean
) {
  addToCart(
    qty: $qty
    pid: $pid
    vid: $vid
    options: $options
    vendor: $vendor
    replace: $replace
  ) {
    items {
      pid
      vid
      barcode
      name
      type
      slug
      qty
      price
      shippingCharge
      tax
      img
      imgCdn
      brandName
      vendor
      vendorSlug
      vendorBusinessName
      deliveryDetails
      options {
        option
        values
      }
      usedOptions {
        name
        val
        dates
      }
    }
    needAddress
    qty
    subtotal
    discount {
      code
      value
      text
      amount
    }
    shipping {
      charge
    }
    tax
    total
  }
}

# for multiple vendor in futute
# {
#   "options": "null",
#   "pid": "61bb679cae9d890438612b83",
#   "qty":1,
#   "vid": "61bb679cae9d890438612b83"
# }

# {
#   "pid": "61bd8d96345c3607b024fe03",
#   "qty":1,
#   "vid": "61bd8d96345c3607b024fe03",
#     "options": [
#       {
#         "option": "61bd8df1345c3607b024fe1f",
#         "values": ["61bd8e30345c3607b024fe2b","61bd8e4d345c3607b024fe35"]
#       }
#       ,{
#       "option":"61bd91d5544e4905248e1396",
#       "values": ["abc","jjjj"]
#       },{
#         "option": "61c2cbad64df9016840108a1",
#         "values": "2022-12-22T07:36:48.709Z"
#       },{
#         "option": "61c2cc2d64df9016840108bc",
#         "values": ["2022-12-22T07:36:48.709Z","2023-12-22T07:36:48.709Z"]
#       }]
# }
