mutation checkout($address: ID, $slot: ID) {
	checkout(address: $address, slot: $slot) {
		id
		orderNo
		otp
		createdAt
		updatedAt
		payment {
			id
		}
		paymentMode
		paymentStatus
		paymentCurrency
		paymentReferenceId
		paymentOrderId
		paymentReceipt
		invoiceId
		paymentGateway
		codPaid
		baseCodPaid
		amountPaid
		amountDue
		paymentStatus
		paymentMsg
		paymentTime
		paid
		amount {
			qty
			subtotal
			tax
			discount
			total
			shipping
		}
		baseAmount {
			subtotal
			tax
			discount
			total
			shipping
		}
		userFirstName
		userLastName
		userPhone
		userEmail
		store {
			id
			name
		}
		address {
			firstName
			lastName
			town
			city
			state
			zip
			address
			lat
			lng
		}
		items {
			pid
			status
			posInvoiceNo
			itemOrderNo
			name
			barcode
			img
			imgCdn
			slug
			price
			basePrice
			qty
			shippingCharge
			baseShippingCharge
			tax
			baseTax
			subtotal
			baseSubtotal
			total
			baseTotal
			time
			# options
			brandName
			brandImg
			brandImgCdn
			parentBrandName
			parentBrandImg
			parentBrandImgCdn
			color
			size
			vendorAddress {
				firstName
				lastName
				town
				city
				state
				zip
				address
				lat
				lng
			}
			vendor {
				id
				businessName
			}
		}
		orderItems {
			id
		}
	}
}
