query blog($id: String!) {
  blog(id: $id) {
    id
    title
    slug
    active
    excerpt
    content
    published_at
    img
    imgCdn
    createdAt
    updatedAt
    user {
      firstName
      lastName
      avatar
    }
    store {
      id
      name
      email
      phone
    }
  }
}
