query blogs(
  $page: Int
  $search: String
  $limit: Int
  $sort: String
  $store: ID
) {
  blogs(
    page: $page
    search: $search
    limit: $limit
    sort: $sort
    store: $store
  ) {
    count
    page
    pageSize
    data {
      id
      title
      slug
      active
      excerpt
      content
      published_at
      img
      imgCdn
      createdAt
      updatedAt
      user {
        firstName
        lastName
        avatar
      }
      store {
        id
        name
        email
        phone
      }
    }
  }
}
