mutation saveBlog(
  $id: String!
  $title: String
  $slug: String
  $excerpt: String
  $content: String
  $published_at: String
  $img: String
  $tags: [String]
  $active: Boolean
) {
  saveBlog(
    id: $id
    title: $title
    slug: $slug
    excerpt: $excerpt
    content: $content
    published_at: $published_at
    img: $img
    tags: $tags
    active: $active
  ) {
    id
    title
    slug
    active
    excerpt
    content
    published_at
    img
    imgCdn
    tags
    active
  }
}
