query myOrderItems(
  $page: Int
  $skip: Int
  $limit: Int
  $search: String
  $sort: String
  $status: String # Pending, Tracking, Delivered
  $where: String
  $store: ID
) {
  myOrderItems(
    page: $page
    skip: $skip
    limit: $limit
    search: $search
    sort: $sort
    status: $status
    where: $where
    store: $store
  ) {
    count
    pageSize
    page
    data {
      id
      status
      isReplacement
      pid
      usedOptions {
        name
        val
        dates
      }
      posInvoiceNo
      itemOrderNo
      name
      slug
      img
      imgCdn
      foodType
      tracking
      shippingCharge
      price
      qty
      tax
      brandName
      brandImg
      brandImgCdn
      size
      color
      trackingId
      returnTrackingId
      courierName
      returnCourierName
      #order level info
      orderNo
      otp
      createdAt
      paySuccess
      payment {
        id
      }
      paymentMode
      paymentStatus
      paymentCurrency
      paymentReferenceId
      paymentOrderId
      paymentReceipt
      invoiceId
      paymentGateway
      codPaid
      amountPaid
      amountDue
      paymentMsg
      paymentTime
      paid
      userFirstName
      userLastName
      userPhone
      invoiceLink
      returnValidTill
      paymentMode
      paymentAmount
      vendorBusinessName
      vendor {
        id
        slug
        businessName
        banner
        bannerCdn
      }
      user {
        firstName
        lastName
        email
        phone
        role
      }
      address {
        firstName
        lastName
        address
        lat
        lng
      }
      amount {
        qty
        subtotal
        tax
        discount
        total
        shipping
      }
      payment {
        amountPaid
        amountDue
      }
      store {
        id
        name
        email
      }
      orderHistory {
        id
        status
        title
        body
        icon
        public
        index
        time
      }
    }
  }
}
