query orderItem($id: ID!) {
	orderItem(id: $id) {
		id
		orderId
		status
		pid
		usedOptions {
			name
			val
			dates
		}
		posInvoiceNo
		invoiceId
		itemOrderNo
		expectedDeliveryDate
		deliveryDetails
		shippingOrderId
		shippingProvider
		shippingLabelId
		shippingRateId
		shippingTrackingNumber
		shippingTrackingStatus
		shippingTrackingUrlProvider
		shippingLabelUrl
		shippingCommercialInvoiceUrl
		name
		slug
		img
		imgCdn
		tracking
		foodType
		shippingCharge
		price
		basePrice
		qty
		tax
		baseTax
		total
		totalDiscount
		subtotal
		brandName
		brandImg
		brandImgCdn
		size
		color
		trackingId
		returnTrackingId
		courierName
		returnCourierName
		replaceValidTill
		returnValidTill
		returnPolicyExpired
		returnReason
		type
		amountRefunded
		baseAmountRefunded
		refunds {
			message
			qty
			time
			amount
			refundId
		}
		#order level info
		orderNo
		otp
		createdAt
		paySuccess
		payment {
			id
		}
		paymentMode
		paymentStatus
		paymentCurrency
		paymentReferenceId
		paymentOrderId
		paymentReceipt
		invoiceId
		paymentGateway
		codPaid
		baseCodPaid
		amountPaid
		amountDue
		totalAmountRefunded
		baseTotalAmountRefunded
		paymentMsg
		paymentTime
		paid
		userFirstName
		userLastName
		userPhone
		userEmail
		invoiceLink
		discount
		baseDiscount
		totalDiscount
		baseTotalDiscount
		weight
		unit
		amount {
			total
			discount
			totalDiscount
			subtotal
		}
		baseAmount {
			total
			discount
			totalDiscount
			subtotal
		}
		user {
			id
			firstName
		}
		address {
			firstName
			lastName
			town
			city
			state
			zip
			address
			lat
			lng
		}

		store {
			id
			name
			email
		}
		slot {
			name
			value
			info
			active
		}
		vendor {
			id
			slug
			businessName
			banner
			bannerCdn
		}
		vendorBusinessName
		vendorPhone
		vendorEmail
		vendorCommissionType
		vendorCommissionValue
		vendorAddress {
			firstName
			lastName
			town
			city
			state
			zip
			address
			lat
			lng
		}
		formattedSubtotal
		formattedShippingCharge
		formattedMrp
		formattedAmountRefunded
		formattedPrice
		formattedTax
		formattedTotal
		formattedTotalDiscount
		formattedVendorCommission
		formattedAmountDue
		formattedAmountPaid
		formattedCodPaid
		formattedDiscount
		formattedPaymentAmount
		formattedTotalAmountRefunded
		formattedAmount {
			subtotal
			tax
			discount
			shipping
			total
			totalDiscount
			exchangeRate
		}
		orderHistory {
			id
			status
			title
			body
			icon
			public
			index
			time
		}
	}
}
