mutation paySuccessPageHit($orderId: ID, $paymentReferenceId: String) {
  paySuccessPageHit(
    orderId: $orderId
    paymentReferenceId: $paymentReferenceId
  ) {
    id
    orderNo
    otp
    createdAt
    paySuccess
    paymentMode
    paymentStatus
    paymentCurrency
    paymentReferenceId
    paymentOrderId
    paymentReceipt
    invoiceId
    paymentGateway
    codPaid
    baseCodPaid
    amountPaid
    amountDue
    paymentMsg
    paymentTime
    paid
    totalAmountRefunded
    baseTotalAmountRefunded
    amount {
      qty
      subtotal
      tax
      discount
      total
      shipping
    }
    baseAmount {
      qty
      subtotal
      tax
      discount
      total
      shipping
    }
    userFirstName
    userLastName
    userPhone
    userEmail
    address {
      firstName
      lastName
      town
      city
      state
      zip
      address
      lat
      lng
    }
    items {
      id
      pid
      posInvoiceNo
      itemOrderNo
      name
      barcode
      img
      imgCdn
      slug
      foodType
      price
      basePrice
      qty
      shippingCharge
      baseShippingCharge
      tax
      baseTax
      time
      usedOptions {
        name
        val
        dates
      }
      brandName
      brandImg
      color
      size
      status
      type
      returnReason
      status
      amountRefunded
      baseAmountRefunded
      vendorBusinessName
      vendorAddress {
        firstName
        lastName
        town
        city
        state
        zip
        address
        lat
        lng
      }
      orderHistory {
        status
        title
        body
        icon
        public
        index
        time
      }
    }
  }
}
