query categories(
  $page: Int
  $search: String
  $limit: Int
  $sort: String
  $megamenu: Boolean
  $featured: Boolean
  $active: Boolean
  $img: Boolean
  $shopbycategory: Boolean
  $store: ID
) {
  categories(
    page: $page
    search: $search
    limit: $limit
    sort: $sort
    megamenu: $megamenu
    featured: $featured
    active: $active
    img: $img
    shopbycategory: $shopbycategory
    store: $store
  ) {
    count
    page
    pageSize
    data {
      id
      name
      namePath
      categoryId
      parent
      slug
      img
      imgCdn
      banner
      bannerCdn
      level
      link
      metaTitle
      metaDescription
      metaKeywords
      keywords
      position
      megamenu
      active
      featured
      featuredSort
      shopbycategory
      createdAt
      updatedAt
      store
    }
  }
}
