query megamenu(
  $id: ID
  $slug: String
  $search: String
  $sort: String
  $featured: Boolean
  $brand: ID
  $store: ID
) {
  megamenu(
    id: $id
    slug: $slug
    search: $search
    sort: $sort
    featured: $featured
    brand: $brand
    store: $store
  ) {
    id
    name
    slug
    img
    imgCdn
    banner
    bannerCdn
    featured
    link
    children {
      name
      slug
      img
      featured
      link
      children {
        name
        slug
        img
        featured
        link
        children {
          name
          slug
          img
          featured
          link
          children {
            name
            slug
            img
            featured
            link
            children {
              name
              slug
              img
              featured
              link
              children {
                name
                slug
                img
                featured
                children {
                  name
                  slug
                  img
                  featured
                  children {
                    name
                    slug
                    img
                    featured
                    children {
                      name
                      slug
                      img
                      featured
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}

# {
#   "brand": "60b4d95b1515460f94e58d4f"
# }
