query myWishlist($page: Int, $search: String, $limit: Int, $sort: String, $store: ID) {
	myWishlist(page: $page, search: $search, limit: $limit, sort: $sort, store: $store) {
		count
		page
		pageSize
		data {
			id
			active
			createdAt
			updatedAt
			product {
				id
				name
				slug
				img
				price
				mrp
				formattedPrice
				discount
				foodType
				vendor {
					id
					slug
					businessName
					banner
					bannerCdn
				}
				brand {
					id
					name
					img
				}
			}
			variant {
				id
				name
			}
			user {
				id
				firstName
				lastName
			}
			store {
				id
				name
				email
			}
		}
	}
}
