/* AUTO-GENERATED by varni-reskin.
 * In tailwind.config.js: theme: { extend: require('./theme/tailwind.theme.cjs') }
 */
module.exports = {
  "colors": {
    "background": "hsl(var(--background) / <alpha-value>)",
    "foreground": "hsl(var(--foreground) / <alpha-value>)",
    "primary": {
      "DEFAULT": "hsl(var(--primary) / <alpha-value>)",
      "foreground": "hsl(var(--primary-foreground) / <alpha-value>)"
    },
    "secondary": {
      "DEFAULT": "hsl(var(--secondary) / <alpha-value>)",
      "foreground": "hsl(var(--secondary-foreground) / <alpha-value>)"
    },
    "accent": {
      "DEFAULT": "hsl(var(--accent) / <alpha-value>)",
      "foreground": "hsl(var(--accent-foreground) / <alpha-value>)"
    },
    "muted": {
      "DEFAULT": "hsl(var(--muted) / <alpha-value>)",
      "foreground": "hsl(var(--muted-foreground) / <alpha-value>)"
    },
    "card": {
      "DEFAULT": "hsl(var(--card) / <alpha-value>)",
      "foreground": "hsl(var(--card-foreground) / <alpha-value>)"
    },
    "destructive": {
      "DEFAULT": "hsl(var(--destructive) / <alpha-value>)",
      "foreground": "hsl(var(--destructive-foreground) / <alpha-value>)"
    },
    "border": "hsl(var(--border) / <alpha-value>)",
    "input": "hsl(var(--input) / <alpha-value>)",
    "ring": "hsl(var(--ring) / <alpha-value>)",
    "brand": {
      "DEFAULT": "#e8281a",
      "secondary": "#86b7fe",
      "accent": "#0d6efd"
    }
  },
  "fontFamily": {
    "heading": [
      "Playfair Display",
      "serif"
    ],
    "sans": [
      "Poppins",
      "ui-sans-serif",
      "system-ui"
    ],
    "body": [
      "Poppins",
      "ui-sans-serif",
      "system-ui"
    ]
  },
  "borderRadius": {
    "DEFAULT": "var(--radius)",
    "lg": "calc(var(--radius) + 4px)",
    "md": "var(--radius)",
    "sm": "calc(var(--radius) - 2px)"
  },
  "boxShadow": {
    "DEFAULT": "0 0 0 .25rem rgba(13,110,253,.25)"
  },
  "maxWidth": {
    "container": "720px"
  }
};
