query states(
	$page: Int
	$search: String
	$limit: Int
	$sort: String
	$country: ID
	$countryCode: String
) {
	states(
		page: $page
		search: $search
		limit: $limit
		sort: $sort
		country: $country
		countryCode: $countryCode
	) {
		count
		page
		pageSize
		data {
			id
			name
			value
			code
			img
			imgCdn
			flag
			lang
			sort
			active
			createdAt
			updatedAt
		}
	}
}
