query product($id: ID!, $zip: String, $optionValues: [ID]) {
	product(id: $id, zip: $zip, optionValues: $optionValues) {
		id
		slug
		name
		description
		type
		price
		mrp
		discount
		stock
		trackInventory
		tax
		img
		imgCdn
		images
		imagesCdn
		time
		active
		popularity
		position
		ratings
		reviews
		sku
		hsn
		group
		barcode
		gender
		gtin
		condition
		trending
		featured
		hot
		new
		sale
		recommended
		title
		itemId
		warranty
		metaDescription
		keywords
		keywordsA
		ageMin
		ageMax
		ageUnit
		styleCode
		eanNo
		articleCode
		productMasterId
		currency
		manufacturer
		countryOfOrigin
		returnInfo
		link
		gender
		condition
		gtin
		cgst
		sgst
		igst
		sizechart
		batchNo
		mfgDate
		expired
		expiryDate
		isSearchable
		isUnlimited
		totalSold
		preOrder
		zips
		foodType
		deliveryDetails
		slots {
			id
			name
			value
		}
		country {
			id
			name
		}
		sizeGroup {
			_id
			slug
			size {
				name
			}
		}
		colorGroup {
			_id
			slug
			color {
				name
				color_code
			}
		}
		brand {
			id
			name
		}
		parentBrand {
			id
			name
		}
		color {
			id
			name
		}
		size {
			id
			name
		}
		category {
			id
			name
			slug
			pathA {
				name
				slug
			}
		}
		categories {
			id
			name
		}
		categoryPool {
			id
			name
		}
		keyFeatures
		features {
			id
			name
			value
		}
		specifications {
			id
			name
			value
		}
		productDetails {
			id
			name
			value
		}
		channels {
			id
			title
			img
			scheduleDateTime
			user {
				firstName
				lastName
			}
		}
		collections {
			id
			name
			description
			active
			images
			img
			q
			sort
			type
		}
		options {
			id
			name
			inputType
			required
			preselectDefault
			position
			values {
				id
				name
				default
				position
				direction
				isPercent
				value
			}
		}
		vendor {
			id
			slug
			businessName
			banner
			bannerCdn
			ratings
			reviews
			info {
				store
				public
				storePhotos
			}
		}
		relatedProducts {
			id
			name
			slug
			img
		}
		returnInfo
		returnAllowed
		replaceAllowed
		returnValidityInDays
		replaceValidityInDays
		files
		unit
		dimensionUnit
		formattedMrp
		formattedPrice
		createdAt
		updatedAt
	}
}
