query productSlug($slug: String!) {
	productSlug(slug: $slug) {
		id
		name
		description
		metaDescription
		createdAt
		updatedAt
		sku
		hsn
		popularity
		slug
		img
		imgCdn
		images
		imagesCdn
		price
		mrp
		formattedPrice
		formattedMrp
		stock
		isUnlimited
		trackInventory
		ratings
		reviews
		returnInfo
		replaceValidityInDays
		returnAllowed
		replaceValidityInDays
		replaceAllowed
		color {
			id
			name
		}
		size {
			name
		}
		brand {
			name
		}
		vendor {
			id
			slug
			businessName
			banner
			bannerCdn
			ratings
			reviews
			info {
				store
				public
				storePhotos
			}
		}
	}
}
